api_platform:
    title: '%env(resolve:APP_NAME)% API'
    version: 0.0.1
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

        normalization_context:
            skip_null_values: false
        pagination_client_items_per_page: true
        pagination_client_partial: true
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 30

    collection:
        pagination:
            items_per_page_parameter_name: 'limit'
            partial_parameter_name: 'partialPagination'

    keep_legacy_inflector: false
    use_symfony_listeners: true
