-- +goose Up

CREATE SCHEMA desuengine;

-- User

CREATE TABLE desuengine.user (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    username        text                        NOT NULL,
    auth_subject    text
);

CREATE UNIQUE INDEX user_username_key ON desuengine.user
    (lower(username));
ALTER TABLE ONLY desuengine.user ADD CONSTRAINT user_auth_subject_key
    UNIQUE (auth_subject);

ALTER TABLE ONLY desuengine.user ADD CONSTRAINT user_username_check
    CHECK (username <> '' AND length(username) <= 24);
ALTER TABLE ONLY desuengine.user ADD CONSTRAINT user_auth_subject_check
    CHECK (auth_subject <> '' AND length(auth_subject) <= 48);

-- Domain

CREATE TABLE desuengine.domain (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    domain          text                        NOT NULL,
    is_verified     boolean                     NOT NULL DEFAULT false,
    user_id         bigint
);

ALTER TABLE ONLY desuengine.domain ADD CONSTRAINT domain_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES desuengine.user(id) ON DELETE CASCADE;

ALTER TABLE ONLY desuengine.domain ADD CONSTRAINT domain_domain_key
    UNIQUE (domain);

ALTER TABLE ONLY desuengine.domain ADD CONSTRAINT domain_domain_check
    CHECK (domain <> '' AND length(domain) <= 32);

-- Domain Verification

CREATE TABLE desuengine.domain_verification (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    domain_id       bigint                      NOT NULL,
    user_id         bigint                      NOT NULL,
    code            text                        NOT NULL
);

ALTER TABLE ONLY desuengine.domain_verification ADD CONSTRAINT domain_verification_domain_id_fkey
    FOREIGN KEY (domain_id) REFERENCES desuengine.domain(id) ON DELETE CASCADE;
ALTER TABLE ONLY desuengine.domain_verification ADD CONSTRAINT domain_verification_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES desuengine.user(id) ON DELETE CASCADE;

-- Link

CREATE TABLE desuengine.link (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    relative_url    text                        NOT NULL,
    domain_id       bigint                      NOT NULL,
    password_hash   text,
    user_id         bigint
);

ALTER TABLE ONLY desuengine.link ADD CONSTRAINT link_domain_id_fkey
    FOREIGN KEY (domain_id) REFERENCES desuengine.domain(id) ON DELETE CASCADE;
ALTER TABLE ONLY desuengine.link ADD CONSTRAINT link_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES desuengine.user(id) ON DELETE CASCADE;

ALTER TABLE ONLY desuengine.link ADD CONSTRAINT link_relative_url_key
    UNIQUE (relative_url);

ALTER TABLE ONLY desuengine.link ADD CONSTRAINT link_relative_url_check
    CHECK (relative_url <> '' AND length(relative_url) <= 64);
ALTER TABLE ONLY desuengine.link ADD CONSTRAINT link_password_hash_check
    CHECK (length(password_hash) = 60);

-- Link Rule

CREATE TABLE desuengine.link_rule (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    link_id         bigint                      NOT NULL,
    rid             text                        NOT NULL,
    ip_addresses    text[],
    origins         text[],
    language_tags   text[]
);

ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_link_id_fkey
    FOREIGN KEY (link_id) REFERENCES desuengine.link(id) ON DELETE CASCADE;

ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_link_id_rid_key
    UNIQUE (link_id, rid);

ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_rid_check
    CHECK (length(rid) = 26);
ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_ip_addresses_check
    CHECK (
        cardinality(ip_addresses) > 0
        AND array_position(ip_addresses, NULL) is NULL
        AND length(array_to_string(ip_addresses, '')) <= 512
    );
ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_origins_check
    CHECK (
        cardinality(origins) > 0
        AND array_position(origins, NULL) is NULL
        AND length(array_to_string(origins, '')) <= 768
    );
ALTER TABLE ONLY desuengine.link_rule ADD CONSTRAINT link_rule_language_tags_check
    CHECK (
        cardinality(language_tags) > 0
        AND array_position(language_tags, NULL) is NULL
        AND length(array_to_string(language_tags, '')) <= 256
    );

-- Link Target

CREATE TABLE desuengine.link_target (
    id              bigint                      PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at      timestamp with time zone    NOT NULL DEFAULT timezone('UTC', now()),
    updated_at      timestamp with time zone,

    link_id         bigint                      NOT NULL,
    rid             text                        NOT NULL,
    rule_id         bigint,
    url_scheme      text,
    url_domain      text,
    url_path        text,
    url_fragment    text
);

ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_link_id_fkey
    FOREIGN KEY (link_id) REFERENCES desuengine.link(id) ON DELETE CASCADE;
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_rule_id_fkey
    FOREIGN KEY (rule_id) REFERENCES desuengine.link_rule(id) ON DELETE SET NULL;

ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_link_id_rid_key
    UNIQUE (link_id, rid);

ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_rid_check
    CHECK (length(rid) = 26);
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_url_scheme_check
    CHECK (url_scheme <> '' AND length(url_scheme) <= 128);
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_url_domain_check
    CHECK (url_domain <> '' AND length(url_domain) <= 256);
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_url_path_check
    CHECK (url_path <> '' AND length(url_path) <= 512);
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_url_fragment_check
    CHECK (url_fragment <> '' AND length(url_fragment) <= 128);
ALTER TABLE ONLY desuengine.link_target ADD CONSTRAINT link_target_href_check
    CHECK (url_domain IS NOT NULL OR url_path IS NOT NULL);

-- +goose Down

DROP TABLE desuengine.link_target;
DROP TABLE desuengine.link_rule;
DROP TABLE desuengine.link;
DROP TABLE desuengine.link_domain;
DROP TABLE desuengine.user;
DROP SCHEMA desuengine;
